export const STRIPE_CLIENT = 'STRIPE_CLIENT'

export const PAYMENT_SERVICE = 'PAYMENT_SERVICE'

export const USERS_SERVICE = 'USERS_SERVICE'

export const STRIPE_SERVICE = 'STRIPE_SERVICE'

export const CREDIT_CARDS_SERVICE = 'CREDIT_CARDS_SERVICE'

export const SUBSCRIPTION_SERVICE = 'SUBSCRIPTION_SERVICE'

export const PRISMA_SERVICE = 'PRISMA_SERVICE'

export const AUTH_SERVICE = 'AUTH_SERVICE'

export const GUILDS_HTTP_SERVICE = 'GUILDS_HTTP_SERVICE'

export const GUILDS_SERVICE = 'GUILDS_SERVICE'

export const PRODUCTS_SERVICE = 'PRODUCTS_SERVICE'

export const STRIPE_WEBHOOK_SERVICE = 'STRIPE_WEBHOOK_SERVICE'

export const PRICES_SERVICE = 'PRICES_SERVICE'

export const PUB_SUB = 'PUB_SUB'
