export const STRIPE_CLIENT = 'STRIPE_CLIENT'

export const PAYMENT_SERVICE = 'PAYMENT_SERVICE'

export const USERS_SERVICE = 'USERS_SERVICE'

export const STRIPE_SERVICE = 'STRIPE_SERVICE'

export const CREDIT_CARDS_SERVICE = 'CREDIT_CARDS_SERVICE'
